language: python
python:
    - "2.7"
    
before_install:
    - sudo apt-get build-dep python-pygame
    - sudo apt-get install mercurial
    
install:
    - pip install hg+http://bitbucket.org/pygame/pygame
    
virtualenv:
    system_site_packages: true
    
script: nosetests 
