language: python
python:
    - "2.7"
    
dist: trusty

before_install:
    - sudo apt-get build-dep python-pygame mercurial -y
    
install:
    - pip install hg+http://bitbucket.org/pygame/pygame
    
virtualenv:
    system_site_packages: true
    
script: nosetests -v
